### ISSUE TITLE
Thesis Document

### ISSUE THREAD

**Issue by reymon359** [reymon359/full-stack-social-site#3]
Write the Thesis document of the project

Parts of the Thesis:
- [x] Acknowledgments #4 
- [x] Quotes #5 
- [x] Abstract #7 
- [x] Keywords #6 
- [x] Table of contents #8 
- [x] Motivation & Main purpose #9
- [x] List of Figures #10 
- [x] Introduction #11 
- [x] Viability Study #12 
- [x] State of the Art #13
- [x] Objectives #15 
- [x] Methodology #16 
- [x] Analysis & Specification #17 
- [x] Design #18 
- [x] Implementation #19
- [x] Results #20 
- [x] Conclusions #21 
- [x] Future work #22 
- [x] References #23 

Edit 18/06/2020
here is the document thesis finished missing a refactor.
[TFM Ramon Morcillo.docx](https://github.com/reymon359/typescript-graphql-client-server/files/4801245/TFM.Ramon.Morcillo.docx)
